string = "K YZWLNKXKJWGN QUGN ETNMX MPLMZOMXYM K TMMJOXA XEN TKZ ZMQEBMF TZEQ KJKZQ EX KXKJWDOXA KXF MPLJEZM NHM TJEEF ET XMI CXEIJMFAM IHOYH MKYH WMKZ RZOXAG IONH ON"
for c in "ABCDEFGHIJKLMNOPQRSTUVWXYZ":
    print(c, ": ", string.count(c))
